version: "3.5"

networks:
  ip6net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 2001:760::/112

services:
  ns62:
    container_name: ns62
    hostname: ns62
    image: nginx-ssh
    networks:
      ip6net:
        ipv6_address: 2001:760::62
    volumes:
      - /root/uni/RdC/lab/shared/:/var/www/html:Z
    security_opt:
      - label:disable

  ns63:
    container_name: ns63
    hostname: ns63
    image: nginx-ssh
    networks:
      ip6net:
        ipv6_address: 2001:760::63
    volumes:
      - /root/uni/RdC/lab/shared/:/var/www/html:Z
    security_opt:
      - label:disable
